apiVersion: v1
kind: Namespace
metadata:
  name: optica
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: optica-service
  namespace: optica
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<<aws_ccount>>:role/role-with-oidc-self-assume
